# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

Vagrant.configure("2") do |config|

	if Vagrant.has_plugin?("vagrant-vbguest")
		config.vbguest.auto_update = ENV['VAGRANT_GUEST_UPDATE'] || false
	end

    config.vm.define "default", autostart: true, primary: true do |default|
        default.vm.box = "ubuntu/bionic64"

        default.vm.provider "virtualbox" do |vb|
            vb.cpus = 2
            vb.customize ["modifyvm", :id, "--memory", 2048]
            vb.customize ["modifyvm", :id, "--name", "myapp"]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
        default.vm.network :private_network, ip: "192.168.57.37"
        default.vm.hostname = "myapp"
        default.vm.box_check_update = true
        default.ssh.forward_agent = true

        #fix for ansible python version issue in 18.04
        default.vm.provision :shell do |shell|
            shell.inline = "yes | cp -rf /usr/bin/python3 /usr/bin/python"
        end

        default.vm.provision :shell do |shell|
            shell.inline = "touch $1 && chmod 0440 $1 && echo $2 > $1"
            shell.args = %q{/etc/sudoers.d/root_ssh_agent "Defaults    env_keep += \"SSH_AUTH_SOCK\""}
        end

        default.vm.provision "ansible" do |ansible|
            ansible.playbook = "_provision/default.yml"
            ansible.raw_arguments = [
              "--ask-become-pass"
            ]
        end

        default.vm.provision "ansible", run: "always" do |ansible|
            ansible.playbook = "_provision/pre-launch.yml"
            ansible.raw_arguments = [
              "--ask-become-pass"
            ]
        end
    end
end
