# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.box_check_update = false
   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.name = "example"
     vb.memory = "2048"
     vb.cpus = 2
     #VBoxManage customizations
     vb.customize ["modifyvm", :id,"--memory", 2048]
     vb.customize ["modifyvm", :id, "--name", "example"]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end
   config.vm.network :private_network, ip: "192.168.57.42"
   config.vm.hostname = "example"
#   config.vm.synced_folder '.', '/vagrant', disabled: true
#   config.vm.synced_folder ".", "/vagrant",
#       :nfs => true,
#       :mount_options => ['rw','async','noatime','rsize=32768','wsize=32768','proto=udp','udp','nfsvers=3']

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get dist-upgrade -y
  SHELL

  config.vm.provision "shell", path: "provision/install-software.sh"
  config.vm.provision "shell", run: "always", path: "provision/set-up.sh"
end
