---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing common packages
  package: name={{ item }} state=present
  with_items: "{{common.apt_pkgs}}"
  become: true

- name: Install PIP.
  package: name=python-pip state=present
  become: true

- name: Installing PIP pkgs
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{common.pip_packages}}"
  become: true
